services:
  backend:
    build:
      context: .
    container_name: backend
    restart: always
    ports:
      - '8000:80'
    volumes:
      - ./basic/web:/app/basic/web

  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: yiidb
      MYSQL_USER: yii
      MYSQL_PASSWORD: project
      MYSQL_ROOT_PASSWORD: admin111
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    container_name: adminer
    hostname: adminer
